# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan Humble
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for Ryan Humble.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rahumble.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "rahumble/rahumble.github.io"
author:
  avatar: "/assets/images/headshot.jpg"
  location: "Stanford, CA"
  bio: I am a researcher interested in anomaly detection, numerical linear algebra, high performance computing, and several other topics. Currently I am a 4th year PhD student at Stanford's <a href="https://icme.stanford.edu/">ICME</a> working with Professor <a href="https://me.stanford.edu/people/eric-darve">Eric Darve</a>.
  email: ryhumble@stanford.edu
  google_scholar: CYmoZ9EAAAAJ
  github: rahumble
  linkedin: rahumble

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-include-cache

site:
  locale: "en-US"
defaults:
  - scope:
      path: ""
      types: home
    values:
      layout: single
      classes: wide
      author_profile: true
  - scope:
      path: ""
      types: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
